### ISSUE TITLE
How to make the flow layout horizontal instead of vertical 

### ISSUE THREAD

**Issue by ianwhite2** [johntvolk/ExpandableColumnLayout#1]
Hi Sir , I am a noob in iOS development so can you tell me how to make it horizontal flow instead of vertical and can I support iOS 7 also with this ?

**Comment by johntvolk** [comment]
Hi,

It's not currently possible to make the layout horizontal. UICollectionViewFlowLayout has this feature via the scrollDirection property, but since I'm inheriting from UICollectionViewLayout directly I'd have to build it from scratch.

I hadn't considered that feature at all for some reason, but now that you bring it up it seems like an oversight. I'll have to think on it though.

Does that answer your question?
- John

**Comment by johntvolk** [comment]
As far as iOS 7 goes, it should support it unless I'm missing something. UICollectionView was added in iOS 6. I guess one question would be how far back Swift support goes. I'm not sure on the answer to that. Can you think of a reason it wouldn't work on iOS 7?
