### ISSUE TITLE
Can I set direction of each section as horizontal or vertical?

### ISSUE THREAD

**Issue by khunshan** [johntvolk/ExpandableColumnLayout#2]
The collection view drawers are cool. Its really pretty and powerful they grow and shrink. In each expanded drawer can i set direction of collection view as horizontal or vertical?

**Comment by johntvolk** [comment]
Thanks, khunshan.

There's currently no support for a horizontal layout. All sections are laid out vertically. I know UICollectionViewFlowLayout has this feature with regards to the collection as a whole (rather than section by section). I think it makes sense to mirror the UICollectionViewFlowLayout feature since I'm not sure what a section by section implementation would look like. I'd like to do this in the next version.

**Comment by khunshan** [comment]
What if I make a custom UICollectionViewCell and add a UICollectionView into it. And then dequeue each such cell and populate it with appropriate layout, cells and data.

**Comment by johntvolk** [comment]
That's an interesting idea. You could certainly give it a shot. I've never had great luck putting scrolling views inside of other scrolling views, but it may work. ExpandableColumnLayout is going to pin the size of the cell to the width of the screen, but a sub UICollectionView could scroll within that viewport.

Let me know how it works if you try it.

**Comment by khunshan** [comment]
Its possible and I done using UICollectionViews added for each section in one UICollectionView used as container. Each item is a UICollectionView with flow layout to set its direction into Horizontal and Vertical. This is the knowledgebase of my development to do it https://ashfurrow.com/blog/putting-a-uicollectionview-in-a-uitableviewcell/
